### ISSUE TITLE
Need to sort c25k page to include photo of Tony, SueC and SueH

### ISSUE THREAD

**Issue by SueHyson** [Portsmouth-Joggers/website#1]
I need to send Rich an updated version of the C25K page that includes photos of the leaders.

**Comment by ear1grey** [comment]
@SueHyson you can attach files directly to this thread using the paperclip in the toolbar. e.g...
![nopic](https://github.com/user-attachments/assets/2cb91282-d1f9-401e-a981-d5b3387d5581)
