### ISSUE TITLE
Join Us button doesn't work

### ISSUE THREAD

**Issue by SueHyson** [Portsmouth-Joggers/website#6]
On the Join Us page the blue button doesn't do anything.  It should either download the current membership form or link to the new microsoft forms form  (and both need updating to include acceptance from members that they are responsible for their own safety)

**Comment by ear1grey** [comment]
Need a URL for the new form once it's been shared to "anyone with the link".

**Comment by Kuldaen** [comment]
I've added a page with the microsoft form now.

**Comment by Kuldaen** [comment]
767d218b1756978efc17bc2e439b2efc4b545cdb

**Comment by Kuldaen** [comment]
Deployed to https://test.pjc.org.uk/join/joinusform/
